main_listing_addresses = [['"http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2021-04-09/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/belgium/vlg/antwerp/2021-03-26/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/nc/asheville/2021-04-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/greece/attica/athens/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/2021-03-09/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/tx/austin/2021-04-16/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/thailand/central-thailand/bangkok/2021-03-21/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/catalonia/barcelona/2021-04-12/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/sa/barossa-valley/2021-04-26/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/vic/barwon-south-west-vic/2021-03-25/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/china/beijing/beijing/2021-03-21/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/belize/bz/belize/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/lombardia/bergamo/2021-03-29/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/germany/be/berlin/2021-03-12/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/emilia-romagna/bologna/2021-04-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/france/nouvelle-aquitaine/bordeaux/2021-04-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ma/boston/2021-04-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-kingdom/england/bristol/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/fl/broward-county/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/belgium/bru/brussels/2021-03-17/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/argentina/ciudad-aut%C3%B3noma-de-buenos-aires/buenos-aires/2021-03-22/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ma/cambridge/2021-03-25/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/south-africa/wc/cape-town/2021-03-25/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/il/chicago/2021-04-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/nv/clark-county-nv/2021-03-12/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/oh/columbus/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/denmark/hovedstaden/copenhagen/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/greece/crete/crete/2021-03-26/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/tx/dallas/2021-04-17/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/co/denver/2021-03-29/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/ireland/leinster/dublin/2021-04-14/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-kingdom/scotland/edinburgh/2021-03-08/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/pv/euskadi/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/toscana/florence/2021-03-12/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/south-africa/gt/gauteng/2021-03-29/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/switzerland/geneva/geneva/2021-03-26/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/belgium/vlg/ghent/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/catalonia/girona/2021-03-28/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-kingdom/england/greater-manchester/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/hi/hawaii/2021-04-14/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/china/hk/hong-kong/2021-03-17/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/ireland/2021-03-28/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/turkey/marmara/istanbul/2021-03-28/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/nj/jersey-city/2021-03-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/portugal/lisbon/lisbon/2021-04-16/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-kingdom/england/london/2021-04-11/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/los-angeles/2021-04-07/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/france/auvergne-rhone-alpes/lyon/2021-04-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2021-04-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/andaluc%C3%ADa/malaga/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/islas-baleares/mallorca/2021-04-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/vic/melbourne/2021-04-10/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/islas-baleares/menorca/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/mexico/df/mexico-city/2021-03-22/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/lombardy/milan/2021-03-11/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/qc/montreal/2021-04-17/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/malta/2021-03-29/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/germany/bv/munich/2021-03-22/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/campania/naples/2021-04-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/nb/new-brunswick/2021-01-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/la/new-orleans/2021-04-10/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ny/new-york-city/2021-04-07/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/nsw/northern-rivers/2021-03-09/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/new-zealand/2021-03-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/oakland/2021-03-31/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/norway/oslo/oslo/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/on/ottawa/2021-04-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/pacific-grove/2021-03-31/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/france/ile-de-france/paris/2021-04-10/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/or/portland/2021-03-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/portugal/norte/porto/2021-04-16/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/czech-republic/prague/prague/2021-03-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/puglia/puglia/2021-03-28/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/qc/quebec-city/2021-04-11/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ri/rhode-island/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/latvia/riga/riga/2021-03-29/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/brazil/rj/rio-de-janeiro/2021-03-21/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/lazio/rome/2021-04-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/or/salem-or/2021-03-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/san-diego/2021-03-17/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/san-francisco/2021-04-07/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/san-mateo-county/2021-03-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/santa-clara-county/2021-03-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/chile/rm/santiago/2021-03-25/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/wa/seattle/2021-03-18/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/andaluc%C3%ADa/sevilla/2021-03-29/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/china/shanghai/shanghai/2021-02-22/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/sicilia/sicily/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/singapore/sg/singapore/2021-03-25/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/greece/south-aegean/south-aegean/2021-03-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/sweden/stockholms-l%C3%A4n/stockholm/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/nsw/sydney/2021-04-10/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/taiwan/northern-taiwan/taipei/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/tas/tasmania/2021-04-08/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/greece/central-macedonia/thessaloniki/2021-03-20/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/japan/kant%C5%8D/tokyo/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/on/toronto/2021-04-09/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/trentino-alto-adige-s%C3%BCdtirol/trentino/2021-03-30/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2021-03-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/spain/vc/valencia/2021-04-21/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/bc/vancouver/2021-04-12/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/switzerland/vd/vaud/2021-04-08/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/italy/veneto/venice/2021-04-09/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/canada/bc/victoria/2021-03-27/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/austria/vienna/vienna/2021-04-13/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/dc/washington-dc/2021-04-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/australia/wa/western-australia/2021-03-19/data/listings.csv.gz"'],
 ['"http://data.insideairbnb.com/united-states/tn/nashville/2021-02-19/data/listings.csv.gz"']]

listing_names = ['the-netherlands, north-holland, amsterdam',
 'belgium, vlg, antwerp',
 'united-states, nc, asheville',
 'greece, attica, athens',
 'australia',
 'united-states, tx, austin',
 'thailand, central-thailand, bangkok',
 'spain, catalonia, barcelona',
 'australia, sa, barossa-valley',
 'australia, vic, barwon-south-west-vic',
 'china, beijing, beijing',
 'belize, bz, belize',
 'italy, lombardia, bergamo',
 'germany, be, berlin',
 'italy, emilia-romagna, bologna',
 'france, nouvelle-aquitaine, bordeaux',
 'united-states, ma, boston',
 'united-kingdom, england, bristol',
 'united-states, fl, broward-county',
 'belgium, bru, brussels',
 'argentina, ciudad-aut%C3%B3noma-de-buenos-aires, buenos-aires',
 'united-states, ma, cambridge',
 'south-africa, wc, cape-town',
 'united-states, il, chicago',
 'united-states, nv, clark-county-nv',
 'united-states, oh, columbus',
 'denmark, hovedstaden, copenhagen',
 'greece, crete, crete',
 'united-states, tx, dallas',
 'united-states, co, denver',
 'ireland, leinster, dublin',
 'united-kingdom, scotland, edinburgh',
 'spain, pv, euskadi',
 'italy, toscana, florence',
 'south-africa, gt, gauteng',
 'switzerland, geneva, geneva',
 'belgium, vlg, ghent',
 'spain, catalonia, girona',
 'united-kingdom, england, greater-manchester',
 'united-states, hi, hawaii',
 'china, hk, hong-kong',
 'ireland',
 'turkey, marmara, istanbul',
 'united-states, nj, jersey-city',
 'portugal, lisbon, lisbon',
 'united-kingdom, england, london',
 'united-states, ca, los-angeles',
 'france, auvergne-rhone-alpes, lyon',
 'spain, comunidad-de-madrid, madrid',
 'spain, andaluc%C3%ADa, malaga',
 'spain, islas-baleares, mallorca',
 'australia, vic, melbourne',
 'spain, islas-baleares, menorca',
 'mexico, df, mexico-city',
 'italy, lombardy, milan',
 'canada, qc, montreal',
 'malta',
 'germany, bv, munich',
 'italy, campania, naples',
 'canada, nb, new-brunswick',
 'united-states, la, new-orleans',
 'united-states, ny, new-york-city',
 'australia, nsw, northern-rivers',
 'new-zealand',
 'united-states, ca, oakland',
 'norway, oslo, oslo',
 'canada, on, ottawa',
 'united-states, ca, pacific-grove',
 'france, ile-de-france, paris',
 'united-states, or, portland',
 'portugal, norte, porto',
 'czech-republic, prague, prague',
 'italy, puglia, puglia',
 'canada, qc, quebec-city',
 'united-states, ri, rhode-island',
 'latvia, riga, riga',
 'brazil, rj, rio-de-janeiro',
 'italy, lazio, rome',
 'united-states, or, salem-or',
 'united-states, ca, san-diego',
 'united-states, ca, san-francisco',
 'united-states, ca, san-mateo-county',
 'united-states, ca, santa-clara-county',
 'united-states, ca, santa-cruz-county',
 'chile, rm, santiago',
 'united-states, wa, seattle',
 'spain, andaluc%C3%ADa, sevilla',
 'china, shanghai, shanghai',
 'italy, sicilia, sicily',
 'singapore, sg, singapore',
 'greece, south-aegean, south-aegean',
 'sweden, stockholms-l%C3%A4n, stockholm',
 'australia, nsw, sydney',
 'taiwan, northern-taiwan, taipei',
 'australia, tas, tasmania',
 'greece, central-macedonia, thessaloniki',
 'japan, kant%C5%8D, tokyo',
 'canada, on, toronto',
 'italy, trentino-alto-adige-s%C3%BCdtirol, trentino',
 'united-states, mn, twin-cities-msa',
 'spain, vc, valencia',
 'canada, bc, vancouver',
 'switzerland, vd, vaud',
 'italy, veneto, venice',
 'canada, bc, victoria',
 'austria, vienna, vienna',
 'united-states, dc, washington-dc',
 'australia, wa, western-australia',
 'united-states, tn, nashville']

import pandas as pd

def load_listing(dir_value, list_names=False):

 'loads values from inside-airbnb-website, can also load directory options if'
 '"list_values" is set to True: example:' \
 'df, keys = load_listing(dir_value = "the-netherlands, north-holland, amsterdam", list_names=True)'
 'keys loads complete list of "dir_value" options'

 directory = {'the-netherlands, north-holland, amsterdam': 'http://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2021-04-09/data/listings.csv.gz', 'belgium, vlg, antwerp': 'http://data.insideairbnb.com/belgium/vlg/antwerp/2021-03-26/data/listings.csv.gz', 'united-states, nc, asheville': 'http://data.insideairbnb.com/united-states/nc/asheville/2021-04-19/data/listings.csv.gz', 'greece, attica, athens': 'http://data.insideairbnb.com/greece/attica/athens/2021-03-20/data/listings.csv.gz', 'australia': 'http://data.insideairbnb.com/australia/2021-03-09/data/listings.csv.gz', 'united-states, tx, austin': 'http://data.insideairbnb.com/united-states/tx/austin/2021-04-16/data/listings.csv.gz', 'thailand, central-thailand, bangkok': 'http://data.insideairbnb.com/thailand/central-thailand/bangkok/2021-03-21/data/listings.csv.gz', 'spain, catalonia, barcelona': 'http://data.insideairbnb.com/spain/catalonia/barcelona/2021-04-12/data/listings.csv.gz', 'australia, sa, barossa-valley': 'http://data.insideairbnb.com/australia/sa/barossa-valley/2021-04-26/data/listings.csv.gz', 'australia, vic, barwon-south-west-vic': 'http://data.insideairbnb.com/australia/vic/barwon-south-west-vic/2021-03-25/data/listings.csv.gz', 'china, beijing, beijing': 'http://data.insideairbnb.com/china/beijing/beijing/2021-03-21/data/listings.csv.gz', 'belize, bz, belize': 'http://data.insideairbnb.com/belize/bz/belize/2021-03-27/data/listings.csv.gz', 'italy, lombardia, bergamo': 'http://data.insideairbnb.com/italy/lombardia/bergamo/2021-03-29/data/listings.csv.gz', 'germany, be, berlin': 'http://data.insideairbnb.com/germany/be/berlin/2021-03-12/data/listings.csv.gz', 'italy, emilia-romagna, bologna': 'http://data.insideairbnb.com/italy/emilia-romagna/bologna/2021-04-20/data/listings.csv.gz', 'france, nouvelle-aquitaine, bordeaux': 'http://data.insideairbnb.com/france/nouvelle-aquitaine/bordeaux/2021-04-18/data/listings.csv.gz', 'united-states, ma, boston': 'http://data.insideairbnb.com/united-states/ma/boston/2021-04-20/data/listings.csv.gz', 'united-kingdom, england, bristol': 'http://data.insideairbnb.com/united-kingdom/england/bristol/2021-03-20/data/listings.csv.gz', 'united-states, fl, broward-county': 'http://data.insideairbnb.com/united-states/fl/broward-county/2021-03-20/data/listings.csv.gz', 'belgium, bru, brussels': 'http://data.insideairbnb.com/belgium/bru/brussels/2021-03-17/data/listings.csv.gz', 'argentina, ciudad-aut%C3%B3noma-de-buenos-aires, buenos-aires': 'http://data.insideairbnb.com/argentina/ciudad-aut%C3%B3noma-de-buenos-aires/buenos-aires/2021-03-22/data/listings.csv.gz', 'united-states, ma, cambridge': 'http://data.insideairbnb.com/united-states/ma/cambridge/2021-03-25/data/listings.csv.gz', 'south-africa, wc, cape-town': 'http://data.insideairbnb.com/south-africa/wc/cape-town/2021-03-25/data/listings.csv.gz', 'united-states, il, chicago': 'http://data.insideairbnb.com/united-states/il/chicago/2021-04-19/data/listings.csv.gz', 'united-states, nv, clark-county-nv': 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2021-03-12/data/listings.csv.gz', 'united-states, oh, columbus': 'http://data.insideairbnb.com/united-states/oh/columbus/2021-03-20/data/listings.csv.gz', 'denmark, hovedstaden, copenhagen': 'http://data.insideairbnb.com/denmark/hovedstaden/copenhagen/2021-03-27/data/listings.csv.gz', 'greece, crete, crete': 'http://data.insideairbnb.com/greece/crete/crete/2021-03-26/data/listings.csv.gz', 'united-states, tx, dallas': 'http://data.insideairbnb.com/united-states/tx/dallas/2021-04-17/data/listings.csv.gz', 'united-states, co, denver': 'http://data.insideairbnb.com/united-states/co/denver/2021-03-29/data/listings.csv.gz', 'ireland, leinster, dublin': 'http://data.insideairbnb.com/ireland/leinster/dublin/2021-04-14/data/listings.csv.gz', 'united-kingdom, scotland, edinburgh': 'http://data.insideairbnb.com/united-kingdom/scotland/edinburgh/2021-03-08/data/listings.csv.gz', 'spain, pv, euskadi': 'http://data.insideairbnb.com/spain/pv/euskadi/2021-03-30/data/listings.csv.gz', 'italy, toscana, florence': 'http://data.insideairbnb.com/italy/toscana/florence/2021-03-12/data/listings.csv.gz', 'south-africa, gt, gauteng': 'http://data.insideairbnb.com/south-africa/gt/gauteng/2021-03-29/data/listings.csv.gz', 'switzerland, geneva, geneva': 'http://data.insideairbnb.com/switzerland/geneva/geneva/2021-03-26/data/listings.csv.gz', 'belgium, vlg, ghent': 'http://data.insideairbnb.com/belgium/vlg/ghent/2021-03-20/data/listings.csv.gz', 'spain, catalonia, girona': 'http://data.insideairbnb.com/spain/catalonia/girona/2021-03-28/data/listings.csv.gz', 'united-kingdom, england, greater-manchester': 'http://data.insideairbnb.com/united-kingdom/england/greater-manchester/2021-03-20/data/listings.csv.gz', 'united-states, hi, hawaii': 'http://data.insideairbnb.com/united-states/hi/hawaii/2021-04-14/data/listings.csv.gz', 'china, hk, hong-kong': 'http://data.insideairbnb.com/china/hk/hong-kong/2021-03-17/data/listings.csv.gz', 'ireland': 'http://data.insideairbnb.com/ireland/2021-03-28/data/listings.csv.gz', 'turkey, marmara, istanbul': 'http://data.insideairbnb.com/turkey/marmara/istanbul/2021-03-28/data/listings.csv.gz', 'united-states, nj, jersey-city': 'http://data.insideairbnb.com/united-states/nj/jersey-city/2021-03-18/data/listings.csv.gz', 'portugal, lisbon, lisbon': 'http://data.insideairbnb.com/portugal/lisbon/lisbon/2021-04-16/data/listings.csv.gz', 'united-kingdom, england, london': 'http://data.insideairbnb.com/united-kingdom/england/london/2021-04-11/data/listings.csv.gz', 'united-states, ca, los-angeles': 'http://data.insideairbnb.com/united-states/ca/los-angeles/2021-04-07/data/listings.csv.gz', 'france, auvergne-rhone-alpes, lyon': 'http://data.insideairbnb.com/france/auvergne-rhone-alpes/lyon/2021-04-18/data/listings.csv.gz', 'spain, comunidad-de-madrid, madrid': 'http://data.insideairbnb.com/spain/comunidad-de-madrid/madrid/2021-04-13/data/listings.csv.gz', 'spain, andaluc%C3%ADa, malaga': 'http://data.insideairbnb.com/spain/andaluc%C3%ADa/malaga/2021-03-30/data/listings.csv.gz', 'spain, islas-baleares, mallorca': 'http://data.insideairbnb.com/spain/islas-baleares/mallorca/2021-04-18/data/listings.csv.gz', 'australia, vic, melbourne': 'http://data.insideairbnb.com/australia/vic/melbourne/2021-04-10/data/listings.csv.gz', 'spain, islas-baleares, menorca': 'http://data.insideairbnb.com/spain/islas-baleares/menorca/2021-03-30/data/listings.csv.gz', 'mexico, df, mexico-city': 'http://data.insideairbnb.com/mexico/df/mexico-city/2021-03-22/data/listings.csv.gz', 'italy, lombardy, milan': 'http://data.insideairbnb.com/italy/lombardy/milan/2021-03-11/data/listings.csv.gz', 'canada, qc, montreal': 'http://data.insideairbnb.com/canada/qc/montreal/2021-04-17/data/listings.csv.gz', 'malta': 'http://data.insideairbnb.com/malta/2021-03-29/data/listings.csv.gz', 'germany, bv, munich': 'http://data.insideairbnb.com/germany/bv/munich/2021-03-22/data/listings.csv.gz', 'italy, campania, naples': 'http://data.insideairbnb.com/italy/campania/naples/2021-04-20/data/listings.csv.gz', 'canada, nb, new-brunswick': 'http://data.insideairbnb.com/canada/nb/new-brunswick/2021-01-30/data/listings.csv.gz', 'united-states, la, new-orleans': 'http://data.insideairbnb.com/united-states/la/new-orleans/2021-04-10/data/listings.csv.gz', 'united-states, ny, new-york-city': 'http://data.insideairbnb.com/united-states/ny/new-york-city/2021-04-07/data/listings.csv.gz', 'australia, nsw, northern-rivers': 'http://data.insideairbnb.com/australia/nsw/northern-rivers/2021-03-09/data/listings.csv.gz', 'new-zealand': 'http://data.insideairbnb.com/new-zealand/2021-03-18/data/listings.csv.gz', 'united-states, ca, oakland': 'http://data.insideairbnb.com/united-states/ca/oakland/2021-03-31/data/listings.csv.gz', 'norway, oslo, oslo': 'http://data.insideairbnb.com/norway/oslo/oslo/2021-03-27/data/listings.csv.gz', 'canada, on, ottawa': 'http://data.insideairbnb.com/canada/on/ottawa/2021-04-19/data/listings.csv.gz', 'united-states, ca, pacific-grove': 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2021-03-31/data/listings.csv.gz', 'france, ile-de-france, paris': 'http://data.insideairbnb.com/france/ile-de-france/paris/2021-04-10/data/listings.csv.gz', 'united-states, or, portland': 'http://data.insideairbnb.com/united-states/or/portland/2021-03-13/data/listings.csv.gz', 'portugal, norte, porto': 'http://data.insideairbnb.com/portugal/norte/porto/2021-04-16/data/listings.csv.gz', 'czech-republic, prague, prague': 'http://data.insideairbnb.com/czech-republic/prague/prague/2021-03-13/data/listings.csv.gz', 'italy, puglia, puglia': 'http://data.insideairbnb.com/italy/puglia/puglia/2021-03-28/data/listings.csv.gz', 'canada, qc, quebec-city': 'http://data.insideairbnb.com/canada/qc/quebec-city/2021-04-11/data/listings.csv.gz', 'united-states, ri, rhode-island': 'http://data.insideairbnb.com/united-states/ri/rhode-island/2021-03-30/data/listings.csv.gz', 'latvia, riga, riga': 'http://data.insideairbnb.com/latvia/riga/riga/2021-03-29/data/listings.csv.gz', 'brazil, rj, rio-de-janeiro': 'http://data.insideairbnb.com/brazil/rj/rio-de-janeiro/2021-03-21/data/listings.csv.gz', 'italy, lazio, rome': 'http://data.insideairbnb.com/italy/lazio/rome/2021-04-13/data/listings.csv.gz', 'united-states, or, salem-or': 'http://data.insideairbnb.com/united-states/or/salem-or/2021-03-19/data/listings.csv.gz', 'united-states, ca, san-diego': 'http://data.insideairbnb.com/united-states/ca/san-diego/2021-03-17/data/listings.csv.gz', 'united-states, ca, san-francisco': 'http://data.insideairbnb.com/united-states/ca/san-francisco/2021-04-07/data/listings.csv.gz', 'united-states, ca, san-mateo-county': 'http://data.insideairbnb.com/united-states/ca/san-mateo-county/2021-03-18/data/listings.csv.gz', 'united-states, ca, santa-clara-county': 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2021-03-19/data/listings.csv.gz', 'united-states, ca, santa-cruz-county': 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2021-03-30/data/listings.csv.gz', 'chile, rm, santiago': 'http://data.insideairbnb.com/chile/rm/santiago/2021-03-25/data/listings.csv.gz', 'united-states, wa, seattle': 'http://data.insideairbnb.com/united-states/wa/seattle/2021-03-18/data/listings.csv.gz', 'spain, andaluc%C3%ADa, sevilla': 'http://data.insideairbnb.com/spain/andaluc%C3%ADa/sevilla/2021-03-29/data/listings.csv.gz', 'china, shanghai, shanghai': 'http://data.insideairbnb.com/china/shanghai/shanghai/2021-02-22/data/listings.csv.gz', 'italy, sicilia, sicily': 'http://data.insideairbnb.com/italy/sicilia/sicily/2021-03-27/data/listings.csv.gz', 'singapore, sg, singapore': 'http://data.insideairbnb.com/singapore/sg/singapore/2021-03-25/data/listings.csv.gz', 'greece, south-aegean, south-aegean': 'http://data.insideairbnb.com/greece/south-aegean/south-aegean/2021-03-13/data/listings.csv.gz', 'sweden, stockholms-l%C3%A4n, stockholm': 'http://data.insideairbnb.com/sweden/stockholms-l%C3%A4n/stockholm/2021-03-27/data/listings.csv.gz', 'australia, nsw, sydney': 'http://data.insideairbnb.com/australia/nsw/sydney/2021-04-10/data/listings.csv.gz', 'taiwan, northern-taiwan, taipei': 'http://data.insideairbnb.com/taiwan/northern-taiwan/taipei/2021-03-30/data/listings.csv.gz', 'australia, tas, tasmania': 'http://data.insideairbnb.com/australia/tas/tasmania/2021-04-08/data/listings.csv.gz', 'greece, central-macedonia, thessaloniki': 'http://data.insideairbnb.com/greece/central-macedonia/thessaloniki/2021-03-20/data/listings.csv.gz', 'japan, kant%C5%8D, tokyo': 'http://data.insideairbnb.com/japan/kant%C5%8D/tokyo/2021-03-27/data/listings.csv.gz', 'canada, on, toronto': 'http://data.insideairbnb.com/canada/on/toronto/2021-04-09/data/listings.csv.gz', 'italy, trentino-alto-adige-s%C3%BCdtirol, trentino': 'http://data.insideairbnb.com/italy/trentino-alto-adige-s%C3%BCdtirol/trentino/2021-03-30/data/listings.csv.gz', 'united-states, mn, twin-cities-msa': 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2021-03-13/data/listings.csv.gz', 'spain, vc, valencia': 'http://data.insideairbnb.com/spain/vc/valencia/2021-04-21/data/listings.csv.gz', 'canada, bc, vancouver': 'http://data.insideairbnb.com/canada/bc/vancouver/2021-04-12/data/listings.csv.gz', 'switzerland, vd, vaud': 'http://data.insideairbnb.com/switzerland/vd/vaud/2021-04-08/data/listings.csv.gz', 'italy, veneto, venice': 'http://data.insideairbnb.com/italy/veneto/venice/2021-04-09/data/listings.csv.gz', 'canada, bc, victoria': 'http://data.insideairbnb.com/canada/bc/victoria/2021-03-27/data/listings.csv.gz', 'austria, vienna, vienna': 'http://data.insideairbnb.com/austria/vienna/vienna/2021-04-13/data/listings.csv.gz', 'united-states, dc, washington-dc': 'http://data.insideairbnb.com/united-states/dc/washington-dc/2021-04-19/data/listings.csv.gz', 'australia, wa, western-australia': 'http://data.insideairbnb.com/australia/wa/western-australia/2021-03-19/data/listings.csv.gz', 'united-states, tn, nashville': 'http://data.insideairbnb.com/united-states/tn/nashville/2021-02-19/data/listings.csv.gz'}

 if dir_value:
  alpha = directory[dir_value]

  df = pd.read_csv(alpha)
  col_new = dir_value.split()[-1]
  df['City'] = col_new

  if list_names==True:
   return df, directory.keys()

  return df

 return directory.keys()